var number1 = parseInt("1234blue");
var number2 = parseInt("");
var number0 = parseInt(0xA);
var number3 = parseInt("0xA");
var number4 = parseInt(22.5);
var number5 = parseInt("22.5");
var number6 = parseInt("070");
var number7 = parseInt("70");
alert(number1);
alert(number2);
alert(number0);
alert(number3);
alert(number4);
alert(number5);
alert(number6);
alert(number7);
